// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"
)

type Querier interface {
	CountBlogPosts(ctx context.Context) (int64, error)
	CreateBlogPost(ctx context.Context, arg CreateBlogPostParams) (BlogPost, error)
	DeleteBlogPost(ctx context.Context, id int32) error
	GetBlogPost(ctx context.Context, id int32) (BlogPost, error)
	ListBlogPosts(ctx context.Context, arg ListBlogPostsParams) ([]BlogPost, error)
	UpdateBlogPost(ctx context.Context, arg UpdateBlogPostParams) (BlogPost, error)
}

var _ Querier = (*Queries)(nil)
