basePath: /
definitions:
  handlers.Blog:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a server for Go Blog API.
  title: Go Blog API
  version: "1.0"
paths:
  /blogs:
    get:
      consumes:
      - application/json
      description: Get all blogs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.Blog'
            type: array
      summary: Get blogs
      tags:
      - blogs
swagger: "2.0"
